### ISSUE TITLE
emmet가 동작하지 않습니다.

### ISSUE THREAD

**Issue by illite** [3600s/editplus-black-theme#1]
editplus4 에서 emmet가 동작하지 않습니다.
최신 editplus ini 폴더에 파일을 가져와서 넣어도 안됩니다.
세팅 문제인 것 같습니다만 어디인지 찾지 못하겠네요.

에러창은 아래와 같습니다.
ADODB.Stream
파일을 열 수 없습니다.
Line:13001, Column:3

**Comment by 3600s** [comment]
![Editplus 4 디렉토리 지정](http://3600s.github.com/editplus-black-theme/images/setup7.png)

`...`으로 디렉토리를 변경하시는 대신 `가져오기...`버튼을 통해 필요한 파일만 덮어쓰기 해 주시면 Emmet도 동작되는 것을 확인 했습니다. 다만, 기존의 원본파일은 따로 백업해 두시길 바랍니다.
또한, 제가 만든 파일은 기존 Editplus 3를 기준으로 작성된 부분이어서 Editplus 4까지는 대응을 하지 못했고, 앞으로도 업데이트에 따른 대응을 하기 어려운 점 양해 부탁드리겠습니다.
